### ISSUE TITLE
Documentation for Getting Started

### ISSUE THREAD

**Issue by sunjam** [pmusaraj/discourse-jitsi#2]
Hi, thanks for developing this amazing plugin!  I'm curious about expanding the readme file and having access to more documentation.

Thanks!

**Comment by robbyoconnor** [comment]
It's actually super simple -- just add it as a theme component, their screencast is pretty much self documenting. The UX for it pretty clear.

**Comment by sunjam** [comment]
Here are the steps for installation.  Please consider adding them to the readme.  Thank you for releasing this!

### Installation
1. If you try this in a Discourse instance that is not on the latest `tests-passed` commit, you might need to add `https://meet.jit.si/external_api.js` to your `content security policy script src` site setting. 
2.  Browse to Hamburger Menu/Admin/Customize/Themes/Components/Install
![Screenshot_20200329_112735](https://user-images.githubusercontent.com/1787238/77857125-8b17d880-71b0-11ea-87e5-268883b10ae0.png)

2.  Install as _[Theme Component](https://meta.discourse.org/t/how-do-i-install-a-theme-or-theme-component/63682)_ from Git repository
![Screenshot_20200329_112809](https://user-images.githubusercontent.com/1787238/77857150-ada9f180-71b0-11ea-9c04-f29c61a555eb.png)

3. You should be taken automatically to component configuration page.  Otherwise, browse to
Hamburger Menu/Admin/Customize/Themes/Components/
![Screenshot_20200329_113221](https://user-images.githubusercontent.com/1787238/77857308-84d62c00-71b1-11ea-90dd-4cd4a5202497.png)
![Screenshot_20200329_113241](https://user-images.githubusercontent.com/1787238/77857306-80117800-71b1-11ea-8402-7b924889dcc3.png)

5. Enjoy.  Discussion page for the plugin is [here on meta.discourse](https://meta.discourse.org/t/video-call-integration-plugin/133944/)

**Comment by pmusaraj** [comment]
See https://meta.discourse.org/t/jitsi-video-conference-component/146046
